apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: rabbit
  namespace: default
  labels: 
    app: rabbitmq 
spec: 
  selector: 
    matchLabels:
      app: rabbitmq 
  replicas: 1
  template: 
    metadata: 
      name: rabbitmq
      labels: 
        app: rabbitmq
        type: queue
    spec: 
      containers: 
        - name: rabbitmq
          image: onemancalledarmy/rabbitmq:v1.0.0
          ports: 
            - containerPort: 5672