apiVersion: apps/v1
kind: Deployment
metadata:
  name: sizer-python
  labels:
    app: sizer-python
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 3
  #     maxUnavailable: 1
  #     timeoutSeconds: 100
  #     intervalSeconds: 5
  #     updatePeriodSeconds: 5
  selector:
    matchLabels:
      app: sizer-python
  template:
    metadata:
      labels:
        app: sizer-python
    spec:
      containers:
      - name: sizer-python
        # image: ${REGISTRY_URL}/sizer-python:v1.0.1
        image: onemancalledarmy/sizer-python:v1.0.2
        env:
          - name: REDIS_HOST
            value: redis-sys
          - name: REDIS_PORT
            value: "6379"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            # wystawic endpoint
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5