apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-python
  labels:
    app: producer-python
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 3
  #     maxUnavailable: 1
  #     timeoutSeconds: 100
  #     intervalSeconds: 5
  #     updatePeriodSeconds: 5
  selector:
    matchLabels:
      app: producer-python
  template:
    metadata:
      labels:
        app: producer-python
    spec:
      containers:
      - name: producer-python
        # image: ${REGISTRY_URL}/producer-python:v1.0.1
        image: onemancalledarmy/producer-python/v1.0.3
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            # wystawic endpoint
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: consumer
# spec:
#   clusterIP: None
#   ports:
#   - port: 5000
#     targetPort: 4369
#     name: discovery
#   selector:
#     app: consumer
