apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-python
  labels:
    app: producer-python
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 3
  #     maxUnavailable: 1
  #     timeoutSeconds: 100
  #     intervalSeconds: 5
  #     updatePeriodSeconds: 5
  selector:
    matchLabels:
      app: producer-python
  template:
    metadata:
      labels:
        app: producer-python
    spec:
      containers:
      - name: producer-python
        # image: ${REGISTRY_URL}/producer-python:v1.0.1
        image: onemancalledarmy/producer-python:v1.0.4
        env:
          - name: RABBIT_HOST
            value: rabbitmq
          - name: RABBIT_PORT
            value: "5672"
          - name: RABBIT_USERNAME
            value: guest
          - name: RABBIT_PASSWORD
            value: guest        
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5