apiVersion: v1
kind: Service
metadata:
  name: producer-python
spec:
  # clusterIP: producer-python
  ports:
  - port: 5000
    targetPort: 5000
    name: producer-python-svc
  selector:
    app: producer-python