# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: consumer-python
#   labels:
#     app: consumer
# spec:
#   replicas: 1
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 3
#       maxUnavailable: 1
#       timeoutSeconds: 100
#       intervalSeconds: 5
#       updatePeriodSeconds: 5
#   selector:
#     matchLabels:
#       app: consumer
#   template:
#     metadata:
#       labels:
#         app: consumer
#     spec:
#       containers:
#       - name: consumer
#         # image: ${REGISTRY_URL}/consumer:v1.0.1
#         ports:
#         - containerPort: 80
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "100m"
#           limits:
#             memory: "128Mi"
#             cpu: "200m"
#         readinessProbe:
#           httpGet:
#             # wystawic endpoint
#             path: /health
#             port: 8080
#           initialDelaySeconds: 5
#           periodSeconds: 5
# ---
apiVersion: v1
kind: Service
metadata:
  name: producer-python
spec:
  clusterIP: producer-python
  ports:
  - port: 5000
    targetPort: 80
    name: producer-python-svc
  selector:
    app: producer-python