apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-python
  labels:
    app: consumer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
      timeoutSeconds: 100
      intervalSeconds: 5
      updatePeriodSeconds: 5
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        # image: ${REGISTRY_URL}/consumer:v1.0.1
        ports:
        - containerPort: 80
        # env:
        #   - name: RABBIT_HOST
        #     value: rabbit-manager
        #   - name: RABBIT_PORT
        #     value: 5672
        #   - name: RABBIT_USERNAME
        #     value: guest
        #   - name: RABBIT_PASSWORD
        #     value: guest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            # wystawic endpoint
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: consumer
# spec:
#   clusterIP: None
#   ports:
#   - port: 5000
#     targetPort: 4369
#     name: discovery
#   selector:
#     app: consumer
